build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false

style:
  FunctionOnlyReturningConstant:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
